/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_jdbc;

/**
 *
 * @author Mazi
 */
public class NewProduct extends javax.swing.JDialog {
    
    DataBaseHandler dataBase;
    /** Creates new form NewProduct
     * @param parent
     * @param modal
     * @param dataBase */
    
    public NewProduct(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public NewProduct(java.awt.Frame parent, boolean modal, DataBaseHandler dataBase) {
        super(parent, modal);
        initComponents();
        myinit(dataBase);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSubmitNew = new javax.swing.JButton();
        dfsProductName = new javax.swing.JTextField();
        lProductname = new javax.swing.JLabel();
        sCarbs = new javax.swing.JSpinner();
        sProteins = new javax.swing.JSpinner();
        sFat = new javax.swing.JSpinner();
        lCarbs = new javax.swing.JLabel();
        lProteins = new javax.swing.JLabel();
        lFat = new javax.swing.JLabel();
        dfsKcal = new javax.swing.JTextField();
        lKcal = new javax.swing.JLabel();
        lg1 = new javax.swing.JLabel();
        lg2 = new javax.swing.JLabel();
        lg3 = new javax.swing.JLabel();
        lg4 = new javax.swing.JLabel();
        cbChooseCategory2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bSubmitNew.setText("Dodaj produkt");
        bSubmitNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitNewActionPerformed(evt);
            }
        });

        lProductname.setText("Nazwa produktu");

        sCarbs.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sCarbsPropertyChange(evt);
            }
        });

        lCarbs.setText("Węglowodany:");

        lProteins.setText("Białko:");

        lFat.setText("Tłuszcze:");

        lKcal.setText("Kaloryczność");

        lg1.setText("g/100g");

        lg2.setText("g/100g");

        lg3.setText("g/100g");

        lg4.setText("kcal/100g");

        cbChooseCategory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseCategory2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Kategoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bSubmitNew, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dfsKcal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lKcal))
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbChooseCategory2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dfsProductName)
                        .addComponent(lProductname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCarbs)
                    .addComponent(lProteins)
                    .addComponent(lFat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sProteins, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lg2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lg1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sFat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lg4)
                            .addComponent(lg3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lProductname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dfsProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sCarbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCarbs)
                            .addComponent(lg1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sProteins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProteins)
                    .addComponent(lg2)
                    .addComponent(cbChooseCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFat)
                    .addComponent(lg3))
                .addGap(26, 26, 26)
                .addComponent(lKcal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dfsKcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lg4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(bSubmitNew, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sCarbsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sCarbsPropertyChange
        countCalories();
    }//GEN-LAST:event_sCarbsPropertyChange

    private void cbChooseCategory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseCategory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChooseCategory2ActionPerformed

    private void bSubmitNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitNewActionPerformed
        /*
        dodaj do tabeli nowy produkt - pobierz z dfsów wartosci i wykonaj insert
        zamknij dialog
        pokaż komunikat że dodano
        */
        String query = "INSERT INTO `produkty`(`Nazwa`, `Kategoria`, `kcal`, `W`, `B`, `T`) VALUES (" + dfsProductName.getText() 
                + "," + cbChooseCategory2.getSelectedItem().toString() + ",[value-3],[value-4],[value-5],[value-6])";
    }//GEN-LAST:event_bSubmitNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewProduct dialog = new NewProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSubmitNew;
    private javax.swing.JComboBox cbChooseCategory2;
    private javax.swing.JTextField dfsKcal;
    private javax.swing.JTextField dfsProductName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lCarbs;
    private javax.swing.JLabel lFat;
    private javax.swing.JLabel lKcal;
    private javax.swing.JLabel lProductname;
    private javax.swing.JLabel lProteins;
    private javax.swing.JLabel lg1;
    private javax.swing.JLabel lg2;
    private javax.swing.JLabel lg3;
    private javax.swing.JLabel lg4;
    private javax.swing.JSpinner sCarbs;
    private javax.swing.JSpinner sFat;
    private javax.swing.JSpinner sProteins;
    // End of variables declaration//GEN-END:variables

    private float getCalories() {        
        float calories = (int)sCarbs.getValue() + (int)sFat.getValue() + (int)sProteins.getValue();
        return calories;
    }

    private void myinit(DataBaseHandler dataBase) {   
        //this.dataBase = dataBase;
        CalendarDiet.initCbChooseCategory(dataBase);
        
        cbChooseCategory2.setModel(new javax.swing.DefaultComboBoxModel(CalendarDiet.initCbChooseCategory(dataBase)));
        cbChooseCategory2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseCategory2ActionPerformed(evt);
            }
        });
        
    }

    private void countCalories() {
        dfsKcal.setText(Float.toString(getCalories())); 
    }

   
}
